---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mysite-mysql-config
  namespace: default
data:
  my.cnf: |-
    [mysqld]
    default_authentication_plugin=mysql_native_password
---
apiVersion: v1
kind: Secret
metadata:
  name: mysite-drupal-mysql-root-password
  namespace: default
data:
  password: bXktc3VwZXItc2VjcmV0LXBhc3M=
---
apiVersion: mysql.oracle.com/v1alpha1
kind: Cluster
metadata:
  name: mysite-mysql
  namespace: default
spec:
  members: 3
  config:
    name: mysite-mysql-config
  rootPasswordSecret:
    name: mysite-drupal-mysql-root-password
---
apiVersion: drupal.sylus.ca/v1beta1
kind: Droplet
metadata:
  name: mysite
  namespace: default
spec:
  replicas: 1
  image: drupalwxt/site-wxt
  secretRef: mysite
  tlsSecretRef: mysite-tls
  env:
    - name: DRUPAL_DB_HOST
      value: mysite-mysql
    - name: DRUPAL_DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysite-drupal-mysql-root-password
          key: password
  domains:
    - drupal.sylus.ca
