{{- if .Values.rbac.create }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "drupal-operator.fullname" . }}
  labels:
    app: '{{ include "drupal-operator.name" . }}'
    chart: '{{ include "drupal-operator.chart" . }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
subjects:
  - kind: ServiceAccount
    name: {{ template "drupal-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "drupal-operator.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
