{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "drupal-operator.serviceAccountName" . }}
  labels:
    app: '{{ include "drupal-operator.name" . }}'
    chart: '{{ include "drupal-operator.chart" . }}'
    release: '{{ .Release.Name }}'
    heritage: '{{ .Release.Service }}'
{{- end }}

